services:
  rtc-chat:
    build: .
    pull_policy: build
    image: dianudi/rtc-chat
    container_name: rtc-chat
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      default:
        ipv4_address: 192.168.10.13

networks:
  default:
    name: http-proxy-network
    external: true
